# Generated by Django 4.2.6 on 2023-12-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_searchtarget_origin_searchtarget_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtarget',
            name='origin',
            field=models.TextField(choices=[('Twitter', 'Twitter')]),
        ),
    ]
