# Generated by Django 4.2.6 on 2024-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_searchtarget_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtarget',
            name='origin',
            field=models.TextField(blank=True, choices=[('Twitter', 'Twitter')], default=''),
        ),
        migrations.AlterField(
            model_name='searchtarget',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
