# Generated by Django 4.2.6 on 2024-01-16 01:54

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_searchtarget_media_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtarget',
            name='media',
            field=models.FileField(blank=True, upload_to=firstapp.models.get_media_path),
        ),
    ]
