# Generated by Django 4.2.6 on 2024-01-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtarget',
            name='url',
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('search_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_target_url', to='firstapp.searchtarget')),
            ],
        ),
    ]
