# Generated by Django 4.2.6 on 2024-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0006_alter_searchtarget_origin_alter_searchtarget_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtarget',
            name='original_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
