# Generated by Django 4.2.6 on 2024-03-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0016_remove_searchtarget_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='search_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='search_targets.searchtarget'),
        ),
    ]
