# Generated by Django 4.2.6 on 2023-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0003_searchtarget_insertion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtarget',
            name='origin',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchtarget',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
