# Generated by Django 4.2.6 on 2024-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0007_searchtarget_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtarget',
            name='media',
            field=models.FileField(blank=True, upload_to='specs'),
        ),
    ]
