# Generated by Django 4.2.6 on 2024-01-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0008_searchtarget_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtarget',
            name='media',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
