# Generated by Django 4.2.6 on 2024-01-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0010_alter_searchtarget_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtarget',
            name='media',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='media/')),
                ('search_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_targets.searchtarget')),
            ],
        ),
    ]
