# Generated by Django 4.2.6 on 2024-01-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0011_remove_searchtarget_media_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtarget',
            name='media',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
