# Generated by Django 4.2.6 on 2024-01-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0014_remove_searchtarget_media_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('GIF', 'Gif'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default=''),
        ),
    ]
