# Generated by Django 4.2.6 on 2024-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0017_alter_media_search_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtarget',
            name='insertion_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
