# Generated by Django 5.1.1 on 2024-10-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_targets', '0018_alter_searchtarget_insertion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file',
            new_name='file_path',
        ),
    ]
