
name: Roback

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEBUG: True
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ENGINE: django.db.backends.sqlite3
      MEDIA_URL: /media/
      MEDIA_ROOT: ""
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Django search targets tests
      run: |
        python src/manage.py test search_targets.tests
